
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Mutiplechoice extends javax.swing.JFrame {
 

    
    /**
     * Creates new form Mutiplechoice
     */
    public Mutiplechoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalcorrectTXT = new javax.swing.JPanel();
        question4TXT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        question1TXT = new javax.swing.JTextField();
        question4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        question2TXT = new javax.swing.JTextField();
        question5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        question5TXT = new javax.swing.JTextField();
        question3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        question3TXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        totcorrectTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question4TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question4TXTActionPerformed(evt);
            }
        });

        jLabel14.setText("B) Lobster");

        question2.setText("What is my favourite colour?");

        jLabel7.setText("A) Green");

        jLabel9.setText("B) Pink");

        question1TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1TXTActionPerformed(evt);
            }
        });

        question4.setText("What is my favourite food?");

        jLabel11.setText("C) Pasta");

        question1.setText("When is my birthday?");

        jLabel3.setText("A) December 30th");

        jLabel4.setText("B) December 21st");

        jLabel5.setText("C) December 31st");

        jLabel12.setText("A) Pizza");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel13.setText("Rose");

        jLabel1.setText("C) Blue");

        question2TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question2TXTActionPerformed(evt);
            }
        });

        question5.setText("What colour are my eyes?");

        jLabel16.setText("A) Brown");

        jLabel17.setText(" B) Black");

        jLabel18.setText("C) Green");

        question5TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question5TXTActionPerformed(evt);
            }
        });

        question3.setText("Whats my favourite drink?");

        jLabel20.setText("A) Chocolate Milk");

        jLabel21.setText("B) Coffee");

        jLabel22.setText("C) Tea");

        question3TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question3TXTActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        totcorrectTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totcorrectTXTActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Correct:");

        javax.swing.GroupLayout TotalcorrectTXTLayout = new javax.swing.GroupLayout(TotalcorrectTXT);
        TotalcorrectTXT.setLayout(TotalcorrectTXTLayout);
        TotalcorrectTXTLayout.setHorizontalGroup(
            TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question4)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question5)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addComponent(question2)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TotalcorrectTXTLayout.createSequentialGroup()
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(question1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TotalcorrectTXTLayout.createSequentialGroup()
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                        .addComponent(question1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                        .addComponent(question2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TotalcorrectTXTLayout.createSequentialGroup()
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(question4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalcorrectTXTLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(question5TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalcorrectTXTLayout.createSequentialGroup()
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question3)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jButton1)
                            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(question3TXT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalcorrectTXTLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totcorrectTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
            .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );
        TotalcorrectTXTLayout.setVerticalGroup(
            TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1)
                    .addComponent(question2)
                    .addComponent(question3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel20)))
                .addGap(5, 5, 5)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(question1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(question2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(question3TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question4)
                            .addComponent(question5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(totcorrectTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButton1))
                            .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(question5TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(question4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(177, Short.MAX_VALUE))
                    .addGroup(TotalcorrectTXTLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(TotalcorrectTXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalcorrectTXTLayout.createSequentialGroup()
                    .addContainerGap(303, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalcorrectTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalcorrectTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void question1TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question1TXTActionPerformed

    private void question2TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question2TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question2TXTActionPerformed

    private void question3TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question3TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question3TXTActionPerformed

    private void question4TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question4TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question4TXTActionPerformed

    private void question5TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question5TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question5TXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        int totalcorrect = 0;
        int totalincorrect = 0;
        int totalpercent = totalcorrect * 100;
        final String QUESTION1 = "A";
        final String QUESTION2 = "C";
        final String QUESTION3 = "A";
        final String QUESTION4 = "A";
        final String QUESTION5 = "A";
        String user1;
        String user2;
        String user3;
        String user4;
        String user5;
        
        
        
        user1 = question1TXT.getText();
        if (user1.equals(QUESTION1)){
            System.out.println("correct");
            totalcorrect = totalcorrect +1;
            
        } else{
            System.out.println("incorrect");
        }
        
        user2 = question2TXT.getText();
        if (user2.equals(QUESTION2)){
            System.out.println("correct");
              totalcorrect = totalcorrect +1;
        } else{
            System.out.println("incorrect");
        }
        
        user3 = question3TXT.getText();
        if (user3.equals(QUESTION3)){
            System.out.println("correct");
              totalcorrect = totalcorrect +1;
        } else{
            System.out.println("incorrect");
        }
        
        user4 = question4TXT.getText();
        if (user4.equals(QUESTION4)){
            System.out.println("correct");
              totalcorrect = totalcorrect +1;
        } else{
            System.out.println("incorrect");
        }
        
        user5 = question5TXT.getText();
        if (user5.equals(QUESTION5)){
            System.out.println("correct");
              totalcorrect = totalcorrect +1;
        } else{
            System.out.println("incorrect");
        }
         
        totcorrectTXT.setText(String.valueOf(totalcorrect));
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
//        totalpercent = totalpercent * 100;
//        totalpercent = Math.round(totalpercent);
//        totalpercent = totalpercent/100;
//        correctDisplay.setText(":" + totalcorrect);
//        incorrectDisplay.setText(":" + )
//        
                
        
        
            
        
        
        




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totcorrectTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totcorrectTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totcorrectTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mutiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mutiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mutiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mutiplechoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mutiplechoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TotalcorrectTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel question1;
    private javax.swing.JTextField question1TXT;
    private javax.swing.JLabel question2;
    private javax.swing.JTextField question2TXT;
    private javax.swing.JLabel question3;
    private javax.swing.JTextField question3TXT;
    private javax.swing.JLabel question4;
    private javax.swing.JTextField question4TXT;
    private javax.swing.JLabel question5;
    private javax.swing.JTextField question5TXT;
    private javax.swing.JTextField totcorrectTXT;
    // End of variables declaration//GEN-END:variables
}
